tokenizer: "/home/pholur/XXXX-2/src/model/tokenizers/dna_tokenizer_10k.json"

# initialized-with-one-step: "/mnt/SSD5/pholur/checkpoints/checkpoint_initalialized.pt"
# trained-ch2-1000: "/mnt/SSD5/pholur/checkpoints/checkpoint_smooth-rock-29.pt"
# trained-ch2-1000: "/mnt/SSD5/pholur/checkpoints/checkpoint_amber-elevator-53.pt"
trained-ch2-longer: "/mnt/SSD5/pholur/checkpoints/checkpoint_rich-fog-63.pt"

# trained-all: "/mnt/SSD2/pholur/General_Models/checkpoint_exalted-dew-60.pt"
trained-all-longer: "/mnt/SSD5/pholur/checkpoints/checkpoint_major-flower-62.pt"

trained-all-shorter: "/mnt/SSD5/pholur/checkpoints/vocal-paper-2.pt"

dna2bert-mean: "Baseline"
dna2bert-max: "Baseline"
nucleotide-transformer-max: "Baseline"
nucleotide-transformer-mean: "Baseline"
hyena-dna-mean: "Baseline"
hyena-dna-max: "Baseline"



